# Generated by Django 5.0.3 on 2024-03-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('otp', models.CharField(max_length=4)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Doctor Avatar')),
                ('degree', models.CharField(blank=True, max_length=37, null=True)),
                ('role', models.CharField(blank=True, choices=[('HAIRSP', 'Hair Specialist'), ('SKINSP', 'Skin Specialist'), ('NEUROSRGN', 'Neurosurgeon'), ('DENTIST', 'Dentist'), ('EYESP', 'EYE Specialist'), ('EARSP', 'EAR Specialist')], max_length=10, null=True)),
                ('adhar_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('otp', models.CharField(max_length=4)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Patient Avatar')),
                ('suggetion', models.CharField(max_length=255)),
                ('next_appointment', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
