# Generated by Django 5.0.3 on 2024-03-27 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistration',
            name='disease',
            field=models.ManyToManyField(to='Project.disease'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='regestered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.doctorregistration'),
        ),
    ]
