# Generated by Django 5.0.3 on 2024-03-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregistration',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
