# Generated by Django 5.0.3 on 2024-03-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('medicine', models.CharField(max_length=255)),
                ('should_do', models.TextField()),
                ('should_not_do', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('degree', models.CharField(max_length=20)),
                ('role', models.CharField(blank=True, choices=[('HAIRSP', 'Hair Specialist'), ('SKINSP', 'Skin Specialist'), ('NEUROSRGN', 'Neurosurgeon'), ('DENTIST', 'Dentist'), ('EYESP', 'EYE Specialist'), ('EARSP', 'EAR Specialist')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('adhar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Doctor Avatar')),
                ('bank_name', models.CharField(blank=True, max_length=25, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('SAC', 'Saving Account'), ('CAC', 'Current Account'), ('FDAC', 'Fixed Deposite Account'), ('SAAC', 'Salary Account'), ('OTAC', 'Other Account')], max_length=4, null=True)),
                ('account_no', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Patient Avatar')),
                ('bank_name', models.CharField(blank=True, max_length=25, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('SAC', 'Saving Account'), ('CAC', 'Current Account'), ('FDAC', 'Fixed Deposite Account'), ('SAAC', 'Salary Account'), ('OTAC', 'Other Account')], max_length=4, null=True)),
                ('account_no', models.CharField(blank=True, max_length=12, null=True)),
                ('suggetion', models.TextField(blank=True, null=True)),
                ('next_appointment', models.CharField(blank=True, max_length=10, null=True)),
                ('disease_name', models.ManyToManyField(to='Project.disease')),
                ('registered_by', models.ManyToManyField(to='Project.doctor')),
            ],
        ),
    ]
