# Generated by Django 5.0.3 on 2024-03-27 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('medicine', models.CharField(max_length=255)),
                ('should_do', models.TextField()),
                ('should_not_do', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Additional_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('SAC', 'Saving Account'), ('CAC', 'Current Account'), ('FDAC', 'Fixed Deposite Account'), ('SAAC', 'Salary Account'), ('OTAC', 'Other Account')], max_length=10, null=True)),
                ('account_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('doctor_registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.doctorregistration')),
                ('patient_registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.patientregistration')),
            ],
        ),
    ]
