# Generated by Django 5.0.3 on 2024-03-28 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_remove_doctorregistration_adhar_no_and_more'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_info_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Doctor Avatar')),
                ('degree', models.CharField(blank=True, max_length=37, null=True)),
                ('role', models.CharField(blank=True, choices=[('HAIRSP', 'Hair Specialist'), ('SKINSP', 'Skin Specialist'), ('NEUROSRGN', 'Neurosurgeon'), ('DENTIST', 'Dentist'), ('EYESP', 'EYE Specialist'), ('EARSP', 'EAR Specialist')], max_length=10, null=True)),
                ('adhar_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('doctor_registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.doctorregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Basic_info_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Patient Avatar')),
                ('suggetion', models.CharField(max_length=255)),
                ('next_appointment', models.DateTimeField()),
                ('disease', models.ManyToManyField(to='Project.disease')),
                ('patient_registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.patientregistration')),
            ],
        ),
    ]
