# Generated by Django 5.0.3 on 2024-03-20 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='account_no',
            field=models.CharField(blank=True, default='a', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAC', 'Saving Account'), ('CAC', 'Current Account'), ('FDAC', 'Fixed Deposite Account'), ('SAAC', 'Salary Account'), ('OTAC', 'Other Account')], default='a', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, default='a', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, default='a', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bank_name',
            field=models.CharField(blank=True, default='a', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease_name',
            field=models.ManyToManyField(default='a', to='Project.disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='firstname',
            field=models.CharField(default='a', max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastname',
            field=models.CharField(default='a', max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(default='a', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_appointment',
            field=models.CharField(blank=True, default='a', max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='registered_by',
        ),
        migrations.AlterField(
            model_name='patient',
            name='suggetion',
            field=models.TextField(blank=True, default='a', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='registered_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Project.doctor'),
        ),
    ]
