# Generated by Django 5.0.3 on 2024-03-20 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_patient_account_no_alter_patient_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='account_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAC', 'Saving Account'), ('CAC', 'Current Account'), ('FDAC', 'Fixed Deposite Account'), ('SAAC', 'Salary Account'), ('OTAC', 'Other Account')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bank_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease_name',
            field=models.ManyToManyField(to='Project.disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='firstname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_appointment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='suggetion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
