# Generated by Django 5.0.3 on 2024-03-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_remove_doctor_password_remove_doctor_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='account_no',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAC', 'Saving Account'), ('CAC', 'Current Account'), ('FDAC', 'Fixed Deposite Account'), ('SAAC', 'Salary Account'), ('OTAC', 'Other Account')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='adhar_no',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='firstname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Doctor Avatar'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(blank=True, choices=[('HAIRSP', 'Hair Specialist'), ('SKINSP', 'Skin Specialist'), ('NEUROSRGN', 'Neurosurgeon'), ('DENTIST', 'Dentist'), ('EYESP', 'EYE Specialist'), ('EARSP', 'EAR Specialist')], default='', max_length=10, null=True),
        ),
    ]
