# Generated by Django 5.0.3 on 2024-03-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_alter_doctor_account_no_alter_doctor_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='username',
        ),
    ]
