# Generated by Django 5.0.3 on 2024-03-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_remove_doctor_password_remove_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
