# Generated by Django 5.0.3 on 2024-03-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_alter_doctor_mobile_alter_patient_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='account_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='adhar_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='account_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
